site_name: Cassetta
site_url: https://cassetta.readthedocs.io
repo_url: https://github.com/balbasty/cassetta
edit_uri: blob/main/docs
site_dir: html
docs_dir: docs
theme:
  name: material
  palette:
    primary: teal
    accent: teal
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/hammer
plugins:
- mkdocs-jupyter
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: [.]
        import:
        - https://pytorch.org/docs/stable/objects.inv
        - https://numpy.org/doc/stable/objects.inv
        options:
          docstring_style: numpy
          docstring_section_style: spacy
          docstring_options:
            allow_section_blank_line: True
          merge_init_into_class: True
          separate_signature: True
          members_order: source
          show_source: True
          show_root_heading: True
markdown_extensions:
- admonition
- toc:
    toc_depth: 3
- markdown_grid_tables
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.arithmatex:
    generic: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
extra_css:
  - stylesheets/extra.css
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Home: index.md
- Installation: install.md
- API:
  - cassetta: api/cassetta.md
  - cassetta.models: api/models.md
  - cassetta.backbones: api/backbones.md
  - cassetta.layers: api/layers.md
  - cassetta.losses: api/losses.md
  - cassetta.metrics: api/metrics.md
  - cassetta.training: api/training.md
  - cassetta.inference: api/inference.md
  - cassetta.functional: api/functional.md
  - cassetta.io: api/io.md
  - cassetta.core: api/core.md

watch:
- cassetta
