site_name: Cassetta
site_url: https://cassetta.readthedocs.io
repo_url: https://github.com/balbasty/cassetta
edit_uri: blob/main/docs
site_dir: html
docs_dir: docs
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github
plugins:
- mkdocs-jupyter
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: [..]
        options:
          docstring_style: numpy
          docstring_section_style: spacy
          docstring_options:
            allow_section_blank_line: True
          merge_init_into_class: True
          separate_signature: True
          members_order: source
          show_source: True
          show_root_heading: True
markdown_extensions:
- admonition
- toc:
    toc_depth: 3
- markdown_grid_tables
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.arithmatex:
    generic: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Home: index.md
- Installation: install.md
- API:
  - cassetta: api/index.md
  - cassetta.core: api/core.md
  - cassetta.functional: api/functional.md
  - cassetta.layers: api/layers.md
  - cassetta.losses: api/losses.md
  - cassetta.metrics: api/metrics.md
  - cassetta.models: api/models.md
  - cassetta.training: api/training.md

watch:
- cassetta
